# Generated by Django 4.0.4 on 2022-04-30 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiles', models.FloatField()),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('ceeated_by', models.IntegerField(null=True)),
                ('product_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='IraqiStore.product')),
            ],
        ),
    ]
