# Generated by Django 4.0.4 on 2022-04-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantiles',
            new_name='quantity',
        ),
    ]
