# Generated by Django 4.0.4 on 2022-04-30 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0003_rename_quantiles_inventory_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('pobox', models.IntegerField(null=True)),
                ('zip', models.IntegerField(null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('ceeated_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('pobox', models.IntegerField(null=True)),
                ('zip', models.IntegerField(null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('ceeated_by', models.IntegerField(null=True)),
                ('contact_id', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.contact')),
            ],
        ),
    ]
