# Generated by Django 4.0.4 on 2022-05-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0011_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('wazeLink', models.CharField(blank=True, max_length=255, null=True)),
                ('approvalLink', models.CharField(blank=True, max_length=255, null=True)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.account')),
                ('contactId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.contact')),
            ],
        ),
    ]
