# Generated by Django 4.0.4 on 2022-05-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0012_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quoteItemId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.qutoeitem'),
        ),
    ]
