# Generated by Django 4.0.4 on 2022-05-18 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0015_alter_order_contactid_alter_order_orderdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now, editable=False)),
                ('ceeated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contactId',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.contact'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoteDate',
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
