# Generated by Django 4.0.4 on 2022-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0016_user_alter_inventory_quantity_alter_quote_contactid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
