# Generated by Django 4.0.4 on 2022-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0018_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='qutoeitem',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ceeated_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ceeated_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ceeated_by',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
