# Generated by Django 4.0.4 on 2022-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0019_rename_ceeated_by_account_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
