# Generated by Django 4.0.4 on 2022-05-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0020_account_accountnumber_order_order_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='AccountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Order_number',
            new_name='order_number',
        ),
    ]
