# Generated by Django 4.0.4 on 2022-05-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0023_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='IraqiStore.order'),
        ),
    ]
