# Generated by Django 4.0.4 on 2022-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0024_alter_orderitem_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lov',
            name='language',
            field=models.CharField(blank=True, default='he', max_length=2, null=True),
        ),
    ]
