# Generated by Django 4.0.4 on 2022-05-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0025_lov_language'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lov',
            unique_together={('type', 'name', 'language')},
        ),
    ]
