# Generated by Django 4.0.4 on 2022-05-26 09:39

import IraqiStore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0026_alter_lov_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='accountId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='IraqiStore.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=IraqiStore.models.getOrderUID, max_length=12, null=True),
        ),
    ]
