# Generated by Django 4.0.4 on 2022-06-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0029_remove_contact_accountid_account_contactid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accountid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
