# Generated by Django 4.0.4 on 2022-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0030_contact_accountid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='accountid',
            new_name='accountId',
        ),
    ]
