# Generated by Django 4.0.4 on 2022-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0031_rename_accountid_contact_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qutoeitem',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
