# Generated by Django 4.0.4 on 2022-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0033_notification_user_contactid_notificationrecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
