# Generated by Django 4.0.4 on 2022-06-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0034_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
