# Generated by Django 4.0.4 on 2022-06-10 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0035_remove_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agreementDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contactId', models.IntegerField(blank=True, null=True)),
                ('accountId', models.IntegerField(blank=True, null=True)),
                ('template', models.BooleanField(default=False)),
                ('page1', models.TextField(blank=True, max_length=50, null=True)),
                ('page2', models.TextField(blank=True, max_length=50, null=True)),
                ('page3', models.TextField(blank=True, max_length=50, null=True)),
                ('page4', models.TextField(blank=True, max_length=50, null=True)),
                ('signatureTime', models.DateTimeField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
