# Generated by Django 4.0.4 on 2022-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0036_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='page1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='page2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='page3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='page4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
