# Generated by Django 4.0.4 on 2022-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0037_alter_form_page1_alter_form_page2_alter_form_page3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='filePath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
