# Generated by Django 4.0.4 on 2022-06-13 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0040_legaldocument_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountContact', to='IraqiStore.account')),
                ('contactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactAccount', to='IraqiStore.contact')),
            ],
        ),
    ]
