# Generated by Django 4.0.4 on 2022-06-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0041_accountcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='accountcontacts',
            unique_together={('accountId', 'contactId')},
        ),
    ]
