# Generated by Django 4.0.4 on 2022-06-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0043_order_deliveryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderDate',
            new_name='date',
        ),
    ]
