# Generated by Django 4.0.4 on 2022-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0047_remove_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='orderId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
