# Generated by Django 4.0.4 on 2022-06-18 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0048_delivery_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaldocument',
            old_name='documentName',
            new_name='documentLink',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
