# Generated by Django 4.0.4 on 2022-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0049_rename_documentname_legaldocument_documentlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
