# Generated by Django 4.0.4 on 2022-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0050_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='he', max_length=50, null=True),
        ),
    ]
