# Generated by Django 4.0.4 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0055_rename_img_news_url_alter_news_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
