# Generated by Django 4.0.4 on 2022-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0058_notification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationrecipient',
            old_name='recipientId',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
