# Generated by Django 4.0.4 on 2022-09-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0060_alter_notificationrecipient_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userContact', to='IraqiStore.contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, default='production', max_length=50, null=True),
        ),
    ]
