# Generated by Django 4.0.4 on 2022-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0061_alter_user_contactid_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='qrData',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
