# Generated by Django 4.0.4 on 2022-09-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0062_delivery_qrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='accountId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='contactId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
