# Generated by Django 4.0.4 on 2022-09-22 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0063_alter_delivery_accountid_alter_delivery_contactid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
    ]
