# Generated by Django 4.0.4 on 2022-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IraqiStore', '0064_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='senderId',
            new_name='received',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
